package com.szm.web.persistence.entity;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdIsNull() {
            addCriterion("acs_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdIsNotNull() {
            addCriterion("acs_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdEqualTo(Integer value) {
            addCriterion("acs_user_id =", value, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdNotEqualTo(Integer value) {
            addCriterion("acs_user_id <>", value, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdGreaterThan(Integer value) {
            addCriterion("acs_user_id >", value, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("acs_user_id >=", value, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdLessThan(Integer value) {
            addCriterion("acs_user_id <", value, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("acs_user_id <=", value, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdIn(List<Integer> values) {
            addCriterion("acs_user_id in", values, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdNotIn(List<Integer> values) {
            addCriterion("acs_user_id not in", values, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdBetween(Integer value1, Integer value2) {
            addCriterion("acs_user_id between", value1, value2, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andAcsUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("acs_user_id not between", value1, value2, "acsUserId");
            return (Criteria) this;
        }

        public Criteria andUcNameIsNull() {
            addCriterion("uc_name is null");
            return (Criteria) this;
        }

        public Criteria andUcNameIsNotNull() {
            addCriterion("uc_name is not null");
            return (Criteria) this;
        }

        public Criteria andUcNameEqualTo(String value) {
            addCriterion("uc_name =", value, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameNotEqualTo(String value) {
            addCriterion("uc_name <>", value, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameGreaterThan(String value) {
            addCriterion("uc_name >", value, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameGreaterThanOrEqualTo(String value) {
            addCriterion("uc_name >=", value, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameLessThan(String value) {
            addCriterion("uc_name <", value, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameLessThanOrEqualTo(String value) {
            addCriterion("uc_name <=", value, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameLike(String value) {
            addCriterion("uc_name like", value, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameNotLike(String value) {
            addCriterion("uc_name not like", value, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameIn(List<String> values) {
            addCriterion("uc_name in", values, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameNotIn(List<String> values) {
            addCriterion("uc_name not in", values, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameBetween(String value1, String value2) {
            addCriterion("uc_name between", value1, value2, "ucName");
            return (Criteria) this;
        }

        public Criteria andUcNameNotBetween(String value1, String value2) {
            addCriterion("uc_name not between", value1, value2, "ucName");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andUcIdIsNull() {
            addCriterion("uc_id is null");
            return (Criteria) this;
        }

        public Criteria andUcIdIsNotNull() {
            addCriterion("uc_id is not null");
            return (Criteria) this;
        }

        public Criteria andUcIdEqualTo(Integer value) {
            addCriterion("uc_id =", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdNotEqualTo(Integer value) {
            addCriterion("uc_id <>", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdGreaterThan(Integer value) {
            addCriterion("uc_id >", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("uc_id >=", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdLessThan(Integer value) {
            addCriterion("uc_id <", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdLessThanOrEqualTo(Integer value) {
            addCriterion("uc_id <=", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdIn(List<Integer> values) {
            addCriterion("uc_id in", values, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdNotIn(List<Integer> values) {
            addCriterion("uc_id not in", values, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdBetween(Integer value1, Integer value2) {
            addCriterion("uc_id between", value1, value2, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("uc_id not between", value1, value2, "ucId");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Byte value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Byte value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Byte value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Byte value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Byte value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Byte value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Byte> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Byte> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Byte value1, Byte value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Byte value1, Byte value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andHiIsNull() {
            addCriterion("hi is null");
            return (Criteria) this;
        }

        public Criteria andHiIsNotNull() {
            addCriterion("hi is not null");
            return (Criteria) this;
        }

        public Criteria andHiEqualTo(String value) {
            addCriterion("hi =", value, "hi");
            return (Criteria) this;
        }

        public Criteria andHiNotEqualTo(String value) {
            addCriterion("hi <>", value, "hi");
            return (Criteria) this;
        }

        public Criteria andHiGreaterThan(String value) {
            addCriterion("hi >", value, "hi");
            return (Criteria) this;
        }

        public Criteria andHiGreaterThanOrEqualTo(String value) {
            addCriterion("hi >=", value, "hi");
            return (Criteria) this;
        }

        public Criteria andHiLessThan(String value) {
            addCriterion("hi <", value, "hi");
            return (Criteria) this;
        }

        public Criteria andHiLessThanOrEqualTo(String value) {
            addCriterion("hi <=", value, "hi");
            return (Criteria) this;
        }

        public Criteria andHiLike(String value) {
            addCriterion("hi like", value, "hi");
            return (Criteria) this;
        }

        public Criteria andHiNotLike(String value) {
            addCriterion("hi not like", value, "hi");
            return (Criteria) this;
        }

        public Criteria andHiIn(List<String> values) {
            addCriterion("hi in", values, "hi");
            return (Criteria) this;
        }

        public Criteria andHiNotIn(List<String> values) {
            addCriterion("hi not in", values, "hi");
            return (Criteria) this;
        }

        public Criteria andHiBetween(String value1, String value2) {
            addCriterion("hi between", value1, value2, "hi");
            return (Criteria) this;
        }

        public Criteria andHiNotBetween(String value1, String value2) {
            addCriterion("hi not between", value1, value2, "hi");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNull() {
            addCriterion("user_status is null");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNotNull() {
            addCriterion("user_status is not null");
            return (Criteria) this;
        }

        public Criteria andUserStatusEqualTo(Byte value) {
            addCriterion("user_status =", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotEqualTo(Byte value) {
            addCriterion("user_status <>", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThan(Byte value) {
            addCriterion("user_status >", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_status >=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThan(Byte value) {
            addCriterion("user_status <", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThanOrEqualTo(Byte value) {
            addCriterion("user_status <=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusIn(List<Byte> values) {
            addCriterion("user_status in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotIn(List<Byte> values) {
            addCriterion("user_status not in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusBetween(Byte value1, Byte value2) {
            addCriterion("user_status between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("user_status not between", value1, value2, "userStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 06 23:34:46 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}