package com.szm.web.persistence.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.acs_user_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private Integer acsUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uc_name
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private String ucName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.real_name
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uc_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private Integer ucId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.gender
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.email
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.phone
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.hi
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private String hi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_status
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    private Byte userStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.acs_user_id
     *
     * @return the value of tb_user.acs_user_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public Integer getAcsUserId() {
        return acsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.acs_user_id
     *
     * @param acsUserId the value for tb_user.acs_user_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setAcsUserId(Integer acsUserId) {
        this.acsUserId = acsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uc_name
     *
     * @return the value of tb_user.uc_name
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public String getUcName() {
        return ucName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uc_name
     *
     * @param ucName the value for tb_user.uc_name
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setUcName(String ucName) {
        this.ucName = ucName == null ? null : ucName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.real_name
     *
     * @return the value of tb_user.real_name
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.real_name
     *
     * @param realName the value for tb_user.real_name
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uc_id
     *
     * @return the value of tb_user.uc_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public Integer getUcId() {
        return ucId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uc_id
     *
     * @param ucId the value for tb_user.uc_id
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setUcId(Integer ucId) {
        this.ucId = ucId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.gender
     *
     * @return the value of tb_user.gender
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.gender
     *
     * @param gender the value for tb_user.gender
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone
     *
     * @return the value of tb_user.phone
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone
     *
     * @param phone the value for tb_user.phone
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.hi
     *
     * @return the value of tb_user.hi
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public String getHi() {
        return hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.hi
     *
     * @param hi the value for tb_user.hi
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setHi(String hi) {
        this.hi = hi == null ? null : hi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_status
     *
     * @return the value of tb_user.user_status
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_status
     *
     * @param userStatus the value for tb_user.user_status
     *
     * @mbggenerated Mon Mar 06 23:34:46 CST 2017
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }
}